[package]
name = "macho-analysis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Mach-O analysis helpers"

[dependencies]
macho-core.workspace = true
macho-insn.workspace = true
macho-symbols.workspace = true
macho-dyld.workspace = true
macho-codesign.workspace = true
macho-dwarf.workspace = true
macho-objc.workspace = true
macho-swift.workspace = true
macho-cpp = { workspace = true, features = ["abi", "fixups", "itanium-rtti"] }
macho-header-syntax.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
gimli.workspace = true

[dev-dependencies]
macho-test-support = { path = "../macho-test-support" }
