[workspace]
members = [
    "crates/macho-core",
    "crates/macho-insn",

    "crates/macho-analysis",
    "crates/macho-mutate",

    "crates/macho",
    "crates/macho-cli",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/bryanmatteson/macho"
repository = "https://github.com/bryanmatteson/macho.git"
version = "0.1.0"

[workspace.dependencies]
macho-core = { path = "crates/macho-core", version = "0.1.0" }
macho-insn = { path = "crates/macho-insn", version = "0.1.0" }

macho-analysis = { path = "crates/macho-analysis", version = "0.1.0" }
macho-mutate = { path = "crates/macho-mutate", version = "0.1.0" }

macho = { path = "crates/macho", version = "0.1.0" }
zerocopy = { version = "0.8", features = ["derive"] }
thiserror = "2"
bitflags = "2"
clap = { version = "4", features = ["derive"] }
memmap2 = "0.9"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cpp_demangle = "0.5.1"
gimli = { version = "0.33.1", features = ["read"] }
rustc-demangle = "0.1"
sha2 = "0.10"
iced-x86 = { version = "1.21", default-features = false, features = ["std", "decoder", "encoder", "op_code_info", "instr_info", "intel"] }
bad64 = "0.12"
