[package]
name = "macho-dwarf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "DWARF indexes for Mach-O images"

[dependencies]
macho-core.workspace = true
gimli.workspace = true
thiserror.workspace = true

[dev-dependencies]
macho-test-support.workspace = true
