[package]
    name                   = "macho-mutate"
    version.workspace      = true
    edition.workspace      = true
    rust-version.workspace = true
    license.workspace      = true
    homepage.workspace     = true
    repository.workspace   = true
    description            = "Mach-O mutation and patching"

[features]
    default = ["signing"]
    structural = []
    external-signing = ["dep:sha2"]
    signing = [
        "external-signing",
        "dep:apple-codesign",
        "dep:bytes",
        "dep:signature",
        "dep:x509-certificate",
        "dep:zeroize",
    ]

[dependencies]
    apple-codesign = { workspace = true, optional = true }
    bytes = { workspace = true, optional = true }
    macho-core.workspace = true
    macho-codesign.workspace = true
    serde.workspace = true
    sha2 = { workspace = true, optional = true }
    signature = { workspace = true, optional = true }
    zerocopy.workspace = true
    thiserror.workspace = true
    x509-certificate = { workspace = true, optional = true }
    zeroize = { workspace = true, optional = true }

[dev-dependencies]
    macho-test-support = { path = "../macho-test-support" }
