[package]
    name                   = "macho-mutate"
    version.workspace      = true
    edition.workspace      = true
    rust-version.workspace = true
    license.workspace      = true
    homepage.workspace     = true
    repository.workspace   = true
    description            = "Mach-O mutation and patching"

[dependencies]
    macho-core.workspace     = true
    macho-insn.workspace     = true
    macho-analysis.workspace = true
    serde.workspace          = true
    zerocopy.workspace       = true
    sha2.workspace           = true
