//! Allocation-free ARM A64 instruction codec and formatter generated by mkasm v0.2.0.

#![allow(dead_code)]
#![allow(non_snake_case)]

#[rustfmt::skip]
pub mod decoders;
#[rustfmt::skip]
pub mod encoders;
#[rustfmt::skip]
pub mod formatters;

pub use decoders::decode;
pub use encoders::{encode_fixed, encode_with_fields};
pub use formatters::format;
