[package]
name = "macho-codesign"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Mach-O code-signature parsing"
readme = "README.md"

[dependencies]
macho-core.workspace = true
thiserror.workspace = true

[dev-dependencies]
macho-test-support = { path = "../macho-test-support" }
