#![cfg(feature = "cli")]

mod support;

fn cpp_fixture() -> Vec<u8> {
    macho_test_support::thin64_x86_64_with_symbols(&[
        macho_test_support::SymbolFixture {
            name: "__ZN4DemoC1Ev",
            external: true,
            defined: true,
        },
        macho_test_support::SymbolFixture {
            name: "__ZN4DemoD1Ev",
            external: true,
            defined: true,
        },
        macho_test_support::SymbolFixture {
            name: "__ZNK4Demo3runEi",
            external: true,
            defined: true,
        },
    ])
}

#[test]
fn cpp_cli_json_emits_conservative_canonical_recovery() {
    let path = support::temp_file_path("cpp-cli-json");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let output = support::run_cli(["cpp", path.to_str().unwrap(), "--format", "json"]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "cpp CLI failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let envelope: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("JSON envelope");
    let data = &envelope["data"];
    assert_eq!(data["schema_version"], 1);
    assert_eq!(data["language"], "cpp");
    let slice = &data["slices"][0];
    assert_eq!(slice["observations"].as_array().map(Vec::len), Some(3));
    assert_eq!(slice["entities"].as_array().map(Vec::len), Some(4));
    assert!(
        slice["observations"]
            .as_array()
            .unwrap()
            .iter()
            .all(|item| item["disposition"]["kind"] == "included")
    );
}

#[test]
fn cpp_cli_header_emits_only_the_positive_anchor_class_forward() {
    let path = support::temp_file_path("cpp-cli-headers");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let output = support::run_cli(["cpp", path.to_str().unwrap(), "--headers"]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "cpp CLI failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("class Demo;"), "{stdout}");
    assert!(!stdout.contains("Demo::run"), "{stdout}");
}

#[test]
fn cpp_suggest_retains_strict_header_and_ranks_every_blocker() {
    let path = support::temp_file_path("cpp-cli-suggest");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let strict = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--format",
        "json",
    ]);
    let suggest = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--projection-policy",
        "suggest",
        "--format",
        "json",
    ]);
    let _ = std::fs::remove_file(path);
    assert!(
        strict.status.success(),
        "{}",
        String::from_utf8_lossy(&strict.stderr)
    );
    assert!(
        suggest.status.success(),
        "{}",
        String::from_utf8_lossy(&suggest.stderr)
    );
    let strict: serde_json::Value = serde_json::from_slice(&strict.stdout).unwrap();
    let suggest: serde_json::Value = serde_json::from_slice(&suggest.stdout).unwrap();
    let strict_header = &strict["data"]["slices"][0]["header"];
    let suggest_header = &suggest["data"]["slices"][0]["header"];
    assert_eq!(suggest_header["source"], strict_header["source"]);
    assert_eq!(
        suggest_header["assumption_ledger"]["selections"],
        serde_json::json!([])
    );
    assert!(
        suggest_header["assumption_ledger"]["hypotheses"]
            .as_array()
            .unwrap()
            .len()
            >= suggest_header["unresolved"].as_array().unwrap().len()
    );
}

#[test]
fn cpp_best_effort_projects_anchored_public_member_with_receipt() {
    let path = support::temp_file_path("cpp-cli-best-effort");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--projection-policy",
        "best-effort",
        "--format",
        "json",
    ]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let report: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    let header = &report["data"]["slices"][0]["header"];
    let source = header["source"].as_str().unwrap();
    assert!(source.contains("GENERATED BY MACHO USING EXPLICITLY AUTHORIZED ASSUMPTIONS"));
    assert!(source.contains("class Demo"), "{source}");
    assert!(source.contains("public:"), "{source}");
    assert!(source.contains("run(int"), "{source}");
    let receipts = header["assumption_ledger"]["selections"]
        .as_array()
        .unwrap();
    assert_eq!(receipts.len(), 2);
    let owner = receipts
        .iter()
        .find(|receipt| receipt["chosen_candidate_id"] == "class_owner_public")
        .unwrap();
    assert_eq!(owner["evidence_authority"], "heuristic");
    assert_eq!(owner["confidence_basis_points"], 6_500);
    assert_eq!(owner["decision_authority"], "operator_policy");
    assert_eq!(owner["operator_policy"], "best_effort");
    assert_eq!(owner["explicitly_chosen"], false);
    let opaque_return = receipts
        .iter()
        .find(|receipt| receipt["chosen_candidate_id"] == "opaque_return_type")
        .unwrap();
    assert_eq!(opaque_return["evidence_authority"], "heuristic");
    assert_eq!(opaque_return["confidence_basis_points"], 1_000);
}

#[test]
fn cpp_explicit_hypothesis_selections_accept_inline_json_and_toml_input() {
    let path = support::temp_file_path("cpp-cli-explicit-hypotheses");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let discovery = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--projection-policy",
        "best-effort",
        "--format",
        "json",
    ]);
    assert!(discovery.status.success());
    let discovery: serde_json::Value = serde_json::from_slice(&discovery.stdout).unwrap();
    let hypotheses = discovery["data"]["slices"][0]["header"]["assumption_ledger"]["hypotheses"]
        .as_array()
        .unwrap();
    let selection = |candidate_id: &str| {
        let hypothesis = hypotheses
            .iter()
            .find(|hypothesis| {
                hypothesis["candidates"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .any(|candidate| candidate["id"] == candidate_id)
            })
            .unwrap();
        format!(
            "{}={candidate_id}",
            hypothesis["subject"]["key"].as_str().unwrap()
        )
    };
    let owner_selection = selection("class_owner_public");
    let return_selection = selection("opaque_return_type");
    let owner_key = owner_selection.split_once('=').unwrap().0.to_owned();
    let return_key = return_selection.split_once('=').unwrap().0.to_owned();
    let inline_output = support::run_cli(vec![
        "cpp".to_owned(),
        path.to_string_lossy().into_owned(),
        "--headers".to_owned(),
        "--hypothesis-selection".to_owned(),
        owner_selection,
        "--hypothesis-selection".to_owned(),
        return_selection,
        "--format".to_owned(),
        "json".to_owned(),
    ]);
    assert!(
        inline_output.status.success(),
        "{}",
        String::from_utf8_lossy(&inline_output.stderr)
    );

    let selection_path =
        support::temp_file_path("cpp-cli-hypothesis-selections").with_extension("json");
    std::fs::write(
        &selection_path,
        serde_json::to_vec_pretty(&serde_json::json!({
            "schema_version": 1,
            "selections": [
                {
                    "subject": {"domain": "cpp_header", "key": owner_key},
                    "candidate_id": "class_owner_public"
                },
                {
                    "subject": {"domain": "cpp_header", "key": return_key},
                    "candidate_id": "opaque_return_type"
                }
            ]
        }))
        .unwrap(),
    )
    .expect("write selection document");
    let json_output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--hypothesis-selection-file",
        selection_path.to_str().unwrap(),
        "--format",
        "json",
    ]);
    let _ = std::fs::remove_file(selection_path);
    assert!(
        json_output.status.success(),
        "{}",
        String::from_utf8_lossy(&json_output.stderr)
    );

    let toml_path = support::temp_file_path("cpp-cli-hypothesis-selections").with_extension("toml");
    std::fs::write(
        &toml_path,
        format!(
            r#"[selections.cpp_header]
"{owner_key}" = "class_owner_public"
"{return_key}" = "opaque_return_type"
"#
        ),
    )
    .expect("write TOML selection document");
    let toml_output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--hypothesis-selection-file",
        toml_path.to_str().unwrap(),
        "--format",
        "json",
    ]);
    let _ = std::fs::remove_file(path);
    let _ = std::fs::remove_file(toml_path);
    assert!(
        toml_output.status.success(),
        "{}",
        String::from_utf8_lossy(&toml_output.stderr)
    );

    let inline_report: serde_json::Value = serde_json::from_slice(&inline_output.stdout).unwrap();
    let json_report: serde_json::Value = serde_json::from_slice(&json_output.stdout).unwrap();
    let toml_report: serde_json::Value = serde_json::from_slice(&toml_output.stdout).unwrap();
    for report in [&inline_report, &json_report, &toml_report] {
        let header = &report["data"]["slices"][0]["header"];
        assert!(header["source"].as_str().unwrap().contains("class Demo"));
        let receipts = header["assumption_ledger"]["selections"]
            .as_array()
            .unwrap();
        assert_eq!(receipts.len(), 2);
        assert!(
            receipts
                .iter()
                .any(|receipt| { receipt["chosen_candidate_id"] == "class_owner_public" })
        );
        assert!(
            receipts
                .iter()
                .any(|receipt| receipt["chosen_candidate_id"] == "opaque_return_type")
        );
        for receipt in receipts {
            assert_eq!(receipt["operator_policy"], "strict");
            assert_eq!(receipt["decision_authority"], "explicit_operator_choice");
            assert_eq!(receipt["explicitly_chosen"], true);
        }
    }
    assert_eq!(
        inline_report["data"]["slices"][0]["header"],
        json_report["data"]["slices"][0]["header"]
    );
    assert_eq!(
        inline_report["data"]["slices"][0]["header"],
        toml_report["data"]["slices"][0]["header"]
    );
}

#[test]
fn cpp_projection_policy_and_overrides_are_bound_into_the_request_digest() {
    let path = support::temp_file_path("cpp-cli-request-digest");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let run = |policy: &str| {
        support::run_cli([
            "cpp",
            path.to_str().unwrap(),
            "--headers",
            "--projection-policy",
            policy,
            "--format",
            "json",
        ])
    };
    let strict = run("strict");
    let best_effort = run("best-effort");
    assert!(strict.status.success());
    assert!(best_effort.status.success());
    let strict: serde_json::Value = serde_json::from_slice(&strict.stdout).unwrap();
    let best_effort: serde_json::Value = serde_json::from_slice(&best_effort.stdout).unwrap();
    assert_ne!(
        strict["data"]["slices"][0]["resolved_plan"]["request_digest"],
        best_effort["data"]["slices"][0]["resolved_plan"]["request_digest"]
    );
    assert_eq!(
        best_effort["data"]["request"]["hypothesis_selection_policy"]["mode"],
        "best_effort"
    );
    let owner = best_effort["data"]["slices"][0]["header"]["assumption_ledger"]["hypotheses"]
        .as_array()
        .unwrap()
        .iter()
        .find(|hypothesis| {
            hypothesis["candidates"]
                .as_array()
                .unwrap()
                .iter()
                .any(|candidate| candidate["id"] == "class_owner_public")
        })
        .unwrap();
    let explicit = support::run_cli(vec![
        "cpp".to_owned(),
        path.to_string_lossy().into_owned(),
        "--headers".to_owned(),
        "--hypothesis-selection".to_owned(),
        format!(
            "{}=class_owner_public",
            owner["subject"]["key"].as_str().unwrap()
        ),
        "--format".to_owned(),
        "json".to_owned(),
    ]);
    let _ = std::fs::remove_file(path);
    assert!(explicit.status.success());
    let explicit: serde_json::Value = serde_json::from_slice(&explicit.stdout).unwrap();
    assert_ne!(
        strict["data"]["slices"][0]["resolved_plan"]["request_digest"],
        explicit["data"]["slices"][0]["resolved_plan"]["request_digest"]
    );
    assert_eq!(
        explicit["data"]["request"]["hypothesis_selection_policy"]["overrides"]
            .as_array()
            .unwrap()
            .len(),
        1
    );
}

#[test]
fn cpp_partial_owner_selection_preserves_the_downstream_return_blocker() {
    let path = support::temp_file_path("cpp-cli-partial-selection");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let suggest = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--projection-policy",
        "suggest",
        "--format",
        "json",
    ]);
    assert!(suggest.status.success());
    let suggest: serde_json::Value = serde_json::from_slice(&suggest.stdout).unwrap();
    let owner = suggest["data"]["slices"][0]["header"]["assumption_ledger"]["hypotheses"]
        .as_array()
        .unwrap()
        .iter()
        .find(|hypothesis| {
            hypothesis["candidates"]
                .as_array()
                .unwrap()
                .iter()
                .any(|candidate| candidate["id"] == "class_owner_public")
        })
        .unwrap();
    let selection = format!(
        "{}=class_owner_public",
        owner["subject"]["key"].as_str().unwrap()
    );
    let output = support::run_cli(vec![
        "cpp".to_owned(),
        path.to_string_lossy().into_owned(),
        "--headers".to_owned(),
        "--hypothesis-selection".to_owned(),
        selection,
        "--format".to_owned(),
        "json".to_owned(),
    ]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let output: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    let header = &output["data"]["slices"][0]["header"];
    assert!(header["unresolved"].as_array().unwrap().iter().any(|gap| {
        gap["entity_id"] == owner["candidates"][0]["consequences"][0]["subject"]
            && gap["field"] == "return_type"
    }));
}

#[test]
fn cpp_member_only_qualifiers_exclude_the_namespace_candidate() {
    let path = support::temp_file_path("cpp-cli-member-owner");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--projection-policy",
        "suggest",
        "--format",
        "json",
    ]);
    let _ = std::fs::remove_file(path);
    assert!(output.status.success());
    let output: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    let owner = output["data"]["slices"][0]["header"]["assumption_ledger"]["hypotheses"]
        .as_array()
        .unwrap()
        .iter()
        .find(|hypothesis| {
            hypothesis["candidates"]
                .as_array()
                .unwrap()
                .iter()
                .any(|candidate| candidate["id"] == "class_owner_public")
        })
        .unwrap();
    assert_eq!(owner["candidates"].as_array().unwrap().len(), 1);
    assert_eq!(owner["candidates"][0]["id"], "class_owner_public");
}

#[test]
fn cpp_best_effort_projects_an_unqualified_function_with_a_per_gap_opaque_type() {
    let path = support::temp_file_path("cpp-cli-free-function");
    std::fs::write(
        &path,
        macho_test_support::thin64_x86_64_with_symbols(&[macho_test_support::SymbolFixture {
            name: "__Z3foov",
            external: true,
            defined: true,
        }]),
    )
    .expect("write fixture");
    let output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--projection-policy",
        "best-effort",
        "--format",
        "json",
    ]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let envelope: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    let header = &envelope["data"]["slices"][0]["header"];
    let receipt = header["assumption_ledger"]["selections"]
        .as_array()
        .unwrap()
        .iter()
        .find(|receipt| receipt["chosen_candidate_id"] == "opaque_return_type")
        .unwrap();
    let opaque = format!(
        "macho_unknown_return_{}",
        receipt["subject"]["key"].as_str().unwrap()
    );
    let source = header["source"].as_str().unwrap();
    assert!(source.contains(&format!("class {opaque};")), "{source}");
    assert!(source.contains(&format!("{opaque} foo(")), "{source}");
    assert!(
        !source.contains(&format!("class {opaque} foo(")),
        "{source}"
    );
    assert!(!source.contains("__macho"), "{source}");
}

#[test]
fn cpp_report_validation_rejects_a_guessed_declaration_without_its_receipts() {
    let path = support::temp_file_path("cpp-cli-receipt-validation");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--projection-policy",
        "best-effort",
        "--format",
        "json",
    ]);
    let _ = std::fs::remove_file(path);
    assert!(output.status.success());
    let envelope: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    let mut report: macho::analysis::report::RecoveryReport =
        serde_json::from_value(envelope["data"].clone()).unwrap();
    let mut mismatched_choice = report.clone();
    let declaration = mismatched_choice.slices.as_mut_slice()[0]
        .header
        .as_mut()
        .unwrap()
        .declarations
        .iter_mut()
        .find(|declaration| {
            matches!(
                declaration,
                macho::analysis::report::HeaderDecl::Function {
                    owner: Some(owner),
                    ..
                } if owner.terminal_kind() == macho::analysis::report::HeaderOwnerKind::Class
            )
        })
        .expect("best-effort fixture projects a selected class owner");
    let macho::analysis::report::HeaderDecl::Function {
        owner: Some(owner), ..
    } = declaration
    else {
        unreachable!("filtered to a function with an owner")
    };
    *owner.scope_kinds.as_mut_slice().last_mut().unwrap() =
        macho::analysis::report::HeaderOwnerKind::Namespace;
    owner.member_access = None;
    assert!(mismatched_choice.validate().is_err());

    report.slices.as_mut_slice()[0]
        .header
        .as_mut()
        .unwrap()
        .assumption_ledger
        .selections
        .clear();
    assert!(report.validate().is_err());

    let mut source_tamper: macho::analysis::report::RecoveryReport =
        serde_json::from_value(envelope["data"].clone()).unwrap();
    source_tamper.slices.as_mut_slice()[0]
        .header
        .as_mut()
        .unwrap()
        .source
        .push_str("int fabricated_without_a_receipt();\n");
    assert!(source_tamper.validate().is_err());
}

#[test]
fn cpp_cli_header_preserves_proven_namespace_ownership() {
    let path = support::temp_file_path("cpp-cli-namespace");
    std::fs::write(
        &path,
        macho_test_support::thin64_x86_64_with_symbols(&[macho_test_support::SymbolFixture {
            name: "__ZN4Tool3runEi",
            external: true,
            defined: true,
        }]),
    )
    .expect("write fixture");
    let headers = tempfile::tempdir().expect("header root");
    std::fs::write(
        headers.path().join("tool.hpp"),
        "namespace Tool { int run(int value); }\n",
    )
    .expect("write header");
    let root = format!("headers={}", headers.path().display());
    let output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--header-root",
        &root,
    ]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "cpp CLI failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("namespace Tool {"), "{stdout}");
    assert!(stdout.contains("int run(int value);"), "{stdout}");
}

#[test]
fn cpp_cli_header_projects_a_correlated_public_class_member() {
    let path = support::temp_file_path("cpp-cli-class-member");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let headers = tempfile::tempdir().expect("header root");
    std::fs::write(
        headers.path().join("demo.hpp"),
        "class Demo { public: int run(int value) const; };\n",
    )
    .expect("write header");
    let root = format!("headers={}", headers.path().display());
    let output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--header-root",
        &root,
    ]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "cpp CLI failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("class Demo {"), "{stdout}");
    assert!(stdout.contains("public:"), "{stdout}");
    assert!(stdout.contains("int run(int value) const;"), "{stdout}");
    assert!(!stdout.contains("Demo::run"), "{stdout}");
}

#[test]
fn cpp_cli_header_preserves_a_correlated_struct_owner() {
    let path = support::temp_file_path("cpp-cli-struct-member");
    std::fs::write(
        &path,
        macho_test_support::thin64_x86_64_with_symbols(&[macho_test_support::SymbolFixture {
            name: "__ZN4Demo3runEi",
            external: true,
            defined: true,
        }]),
    )
    .expect("write fixture");
    let headers = tempfile::tempdir().expect("header root");
    std::fs::write(
        headers.path().join("demo.hpp"),
        "struct Demo { int run(int value); };\n",
    )
    .expect("write header");
    let root = format!("headers={}", headers.path().display());
    let output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--header-root",
        &root,
    ]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "cpp CLI failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("struct Demo {"), "{stdout}");
    assert!(stdout.contains("public:"), "{stdout}");
    assert!(stdout.contains("int run(int value);"), "{stdout}");
    assert!(!stdout.contains("class Demo"), "{stdout}");
}

#[test]
fn cpp_cli_header_preserves_a_typed_namespace_class_owner_chain() {
    let path = support::temp_file_path("cpp-cli-nested-class-member");
    std::fs::write(
        &path,
        macho_test_support::thin64_x86_64_with_symbols(&[macho_test_support::SymbolFixture {
            name: "__ZNK4Tool4Demo3runEi",
            external: true,
            defined: true,
        }]),
    )
    .expect("write fixture");
    let headers = tempfile::tempdir().expect("header root");
    std::fs::write(
        headers.path().join("demo.hpp"),
        "namespace Tool { class Demo { public: int run(int value) const; }; }\n",
    )
    .expect("write header");
    let root = format!("headers={}", headers.path().display());
    let output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--header-root",
        &root,
    ]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "cpp CLI failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("namespace Tool {"), "{stdout}");
    assert!(stdout.contains("class Demo {"), "{stdout}");
    assert!(stdout.contains("public:"), "{stdout}");
    assert!(stdout.contains("int run(int value) const;"), "{stdout}");
}

#[test]
fn cpp_cli_header_does_not_correlate_a_same_leaf_from_the_wrong_namespace() {
    let path = support::temp_file_path("cpp-cli-wrong-namespace");
    std::fs::write(
        &path,
        macho_test_support::thin64_x86_64_with_symbols(&[macho_test_support::SymbolFixture {
            name: "__ZN4Tool3runEi",
            external: true,
            defined: true,
        }]),
    )
    .expect("write fixture");
    let headers = tempfile::tempdir().expect("header root");
    std::fs::write(
        headers.path().join("other.hpp"),
        "namespace Other { int run(int value); }\n",
    )
    .expect("write header");
    let root = format!("headers={}", headers.path().display());
    let output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--header-root",
        &root,
    ]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "cpp CLI failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("owner/unproven_owner: 1"), "{stdout}");
    assert!(!stdout.contains("namespace Other"), "{stdout}");
}

#[test]
fn cpp_cli_empty_header_reports_one_exact_blocker_per_source_entity() {
    let path = support::temp_file_path("cpp-cli-qualified-type");
    std::fs::write(
        &path,
        macho_test_support::thin64_x86_64_with_symbols(&[macho_test_support::SymbolFixture {
            name: "__ZTIN4Demo6WidgetE",
            external: true,
            defined: true,
        }]),
    )
    .expect("write fixture");
    let output = support::run_cli(["cpp", path.to_str().unwrap(), "--headers"]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "cpp CLI failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("selected source entities: 1"), "{stdout}");
    assert!(stdout.contains("exact projection blockers: 1"), "{stdout}");
    assert!(stdout.contains("owner/unproven_owner: 1"), "{stdout}");
    assert!(
        stdout.contains("header-infer export --all-header-gaps"),
        "{stdout}"
    );
    assert!(!stdout.contains("layout_fields"), "{stdout}");
}

#[test]
fn cpp_abi_execution_is_bounded_to_the_exact_selected_entity() {
    let path = support::temp_file_path("cpp-cli-abi-selection");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--analysis",
        "abi",
        "--name",
        "*run*",
        "--format",
        "json",
    ]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "cpp CLI failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let envelope: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("JSON envelope");
    let slice = &envelope["data"]["slices"][0];
    let selected = slice["resolved_plan"]["selected_entity_ids"]
        .as_array()
        .expect("selected entity IDs");
    assert_eq!(selected.len(), 1);
    let abi_execution = slice["executions"]
        .as_array()
        .expect("execution ledger")
        .iter()
        .find(|execution| execution["collector"] == "abi_body")
        .expect("ABI execution record");
    assert_eq!(
        abi_execution["target_entity_ids"]
            .as_array()
            .expect("ABI target entity IDs"),
        selected
    );
    assert_eq!(abi_execution["counts"]["selected_targets"], 1);
    for entity in slice["entities"].as_array().expect("entities") {
        if entity["id"] != selected[0] {
            assert!(
                entity["evidence"]
                    .as_array()
                    .expect("entity evidence")
                    .iter()
                    .all(|evidence| evidence["collector"] != "abi_body")
            );
        }
    }
}

#[test]
fn cpp_best_effort_preserves_every_independently_anchored_nested_class() {
    let path = support::temp_file_path("cpp-cli-nested-positive-anchors");
    std::fs::write(
        &path,
        macho_test_support::thin64_x86_64_with_symbols(&[
            macho_test_support::SymbolFixture {
                name: "__ZN5OuterC1Ev",
                external: true,
                defined: true,
            },
            macho_test_support::SymbolFixture {
                name: "__ZN5OuterD1Ev",
                external: true,
                defined: true,
            },
            macho_test_support::SymbolFixture {
                name: "__ZN5Outer5InnerC1Ev",
                external: true,
                defined: true,
            },
            macho_test_support::SymbolFixture {
                name: "__ZN5Outer5InnerD1Ev",
                external: true,
                defined: true,
            },
            macho_test_support::SymbolFixture {
                name: "__ZNK5Outer5Inner3runEi",
                external: true,
                defined: true,
            },
        ]),
    )
    .expect("write fixture");
    let output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--projection-policy",
        "best-effort",
    ]);
    let _ = std::fs::remove_file(path);
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let source = String::from_utf8(output.stdout).unwrap();
    assert!(source.contains("class Outer {"), "{source}");
    assert!(source.contains("class Inner {"), "{source}");
    assert!(!source.contains("namespace Outer"), "{source}");

    let mut compiler = std::process::Command::new("clang++")
        .args(["-x", "c++", "-std=c++20", "-fsyntax-only", "-"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .expect("launch clang++");
    use std::io::Write as _;
    compiler
        .stdin
        .as_mut()
        .unwrap()
        .write_all(source.as_bytes())
        .expect("write generated header to clang++");
    let compiled = compiler.wait_with_output().expect("wait for clang++");
    assert!(
        compiled.status.success(),
        "generated header did not compile:\n{}\n{source}",
        String::from_utf8_lossy(&compiled.stderr)
    );
}

#[test]
fn cpp_selection_file_failures_are_input_diagnostics() {
    let path = support::temp_file_path("cpp-cli-selection-input-errors");
    std::fs::write(&path, cpp_fixture()).expect("write fixture");
    let missing = support::temp_file_path("missing-hypothesis-selection").with_extension("toml");
    let missing_output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--hypothesis-selection-file",
        missing.to_str().unwrap(),
        "--format",
        "json",
    ]);
    assert!(!missing_output.status.success());
    let missing_diagnostic: serde_json::Value =
        serde_json::from_slice(&missing_output.stderr).unwrap();
    assert_eq!(
        missing_diagnostic["diagnostics"][0]["code"],
        "cli.input.failed"
    );

    let stale = support::temp_file_path("stale-hypothesis-selection").with_extension("json");
    std::fs::write(
        &stale,
        br#"{
            "schema_version": 1,
            "selections": [{
                "subject": {"domain": "cpp_header", "key": "stale-gap"},
                "candidate_id": "class_owner_public"
            }]
        }"#,
    )
    .unwrap();
    let stale_output = support::run_cli([
        "cpp",
        path.to_str().unwrap(),
        "--headers",
        "--hypothesis-selection-file",
        stale.to_str().unwrap(),
        "--format",
        "json",
    ]);
    let _ = std::fs::remove_file(path);
    let _ = std::fs::remove_file(stale);
    assert!(!stale_output.status.success());
    let stale_diagnostic: serde_json::Value = serde_json::from_slice(&stale_output.stderr).unwrap();
    assert_eq!(
        stale_diagnostic["diagnostics"][0]["code"],
        "cli.input.failed"
    );
}
