[package]
    description            = "C++ RTTI, vtable, and ABI inference for Mach-O images"
    edition.workspace      = true
    homepage.workspace     = true
    license.workspace      = true
    name                   = "macho-cpp"
    readme                 = "README.md"
    repository.workspace   = true
    rust-version.workspace = true
    version.workspace      = true

[features]
    abi          = ["fixups", "dep:macho-insn"]
    default      = ["abi", "fixups", "itanium-rtti"]
    fixups       = ["dep:macho-dyld"]
    itanium-rtti = ["fixups"]

[dependencies]
    macho-core.workspace     = true
    macho-demangle.workspace = true
    macho-dyld               = { workspace = true, optional = true }
    macho-insn               = { workspace = true, optional = true }
    serde.workspace          = true
    thiserror.workspace      = true

[dev-dependencies]
    macho-test-support.workspace = true
    serde_json.workspace         = true
