[package]
name = "macho-metadata"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Mach-O metadata parsing and higher-level recovered views"

[dependencies]
macho-core.workspace = true
serde.workspace = true
rustc-demangle.workspace = true
cpp_demangle.workspace = true
