[package]
name = "macho-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
macho = { path = "../crates/macho", default-features = false, features = ["dyld-cache", "mutation"] }

[[bin]]
name = "container"
path = "fuzz_targets/container.rs"
test = false
doc = false
bench = false

[[bin]]
name = "load_commands"
path = "fuzz_targets/load_commands.rs"
test = false
doc = false
bench = false

[[bin]]
name = "dyld"
path = "fuzz_targets/dyld.rs"
test = false
doc = false
bench = false

[[bin]]
name = "codesign"
path = "fuzz_targets/codesign.rs"
test = false
doc = false
bench = false

[[bin]]
name = "insn"
path = "fuzz_targets/insn.rs"
test = false
doc = false
bench = false

[[bin]]
name = "mutation"
path = "fuzz_targets/mutation.rs"
test = false
doc = false
bench = false

[[bin]]
name = "cache_fileset"
path = "fuzz_targets/cache_fileset.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
