[package]
name = "macho-workflow"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Semantic before-and-after Mach-O mutation workflows"

[dependencies]
macho-core.workspace = true
macho-analysis.workspace = true
macho-mutate.workspace = true
thiserror.workspace = true

[dev-dependencies]
macho-test-support = { path = "../macho-test-support" }
