[package]
name = "macho-patch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Architecture-aware executable patch and trampoline planning"
readme = "README.md"

[dependencies]
macho-core.workspace = true
macho-insn.workspace = true

[dev-dependencies]
macho-test-support.workspace = true
