//! Allocation-free x86 instruction codec and Intel formatter generated by mkasm v0.2.0.

#![allow(dead_code)]
#![allow(clippy::too_many_arguments)]

#[rustfmt::skip]
mod generated;

pub use generated::*;
