[package]
name = "macho-extract"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Mach-O extraction and recovery helpers"

[dependencies]
macho-core.workspace = true
macho-metadata.workspace = true
serde.workspace = true
serde_json.workspace = true
cpp_demangle.workspace = true
gimli.workspace = true
