[package]
name = "macho-demangle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Process-free Rust, C++, and Swift symbol demangling"
readme = "README.md"

[dependencies]
cpp_demangle.workspace = true
rustc-demangle.workspace = true
swift-demangler.workspace = true
